-- ============================================================
-- 企业知识助手 — v4 ACE 架构初始化脚本
-- 权限模型: User Group → Space → ACE (Group ↔ KB ↔ Role)
-- 数据库: kes
-- ============================================================

-- ============================================================
-- pgvector 扩展
-- ============================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- 认证鉴权（与 v2 基本一致，仅 users 去掉了 department）
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id                UUID         PRIMARY KEY,
    username          VARCHAR(32)  NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    display_name      VARCHAR(64)  NOT NULL,
    is_global_admin   BOOLEAN      DEFAULT FALSE,
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(512)  NOT NULL UNIQUE,
    expires_at  TIMESTAMP     NOT NULL,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rt_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_rt_user ON refresh_tokens(user_id);

-- ============================================================
-- v3: Space（顶层空间）
-- type_label 自由文本，不做枚举约束
-- ============================================================

CREATE TABLE IF NOT EXISTS spaces (
    id                 UUID         PRIMARY KEY,
    name               VARCHAR(128) NOT NULL,
    type_label         VARCHAR(64)  DEFAULT '',             -- 自由文本标签，如 "company"/"lab"/"community"
    description        TEXT         DEFAULT '',
    status             VARCHAR(16)  DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    deleted_at         TIMESTAMP    NULL,
    last_accessed_at   TIMESTAMP,
    created_by         UUID         NOT NULL REFERENCES users(id),
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ============================================================
-- v4: 全局用户组（可嵌套）+ 组成员
-- ============================================================

CREATE TABLE IF NOT EXISTS user_groups (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_group_id  UUID         REFERENCES user_groups(id) ON DELETE SET NULL,
    name             VARCHAR(128) NOT NULL,
    description      TEXT         DEFAULT '',
    is_system_admin  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by       UUID         NOT NULL REFERENCES users(id),
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_groups_parent ON user_groups(parent_group_id);

CREATE TABLE IF NOT EXISTS user_group_members (
    id         UUID       PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id   UUID       NOT NULL REFERENCES user_groups(id) ON DELETE CASCADE,
    user_id    UUID       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at  TIMESTAMP  NOT NULL DEFAULT NOW(),
    UNIQUE(group_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_ugm_user  ON user_group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_ugm_group ON user_group_members(group_id);

-- ============================================================
-- v4: 角色定义（KB 级别权限套餐）
-- ============================================================

CREATE TABLE IF NOT EXISTS roles (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name         VARCHAR(64)  NOT NULL,
    description  TEXT         DEFAULT '',
    permissions  JSONB        NOT NULL DEFAULT '{}',
    is_system    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 预置 4 个系统角色
INSERT INTO roles (id, name, description, permissions, is_system) VALUES
    ('dddddddd-0000-4000-d000-000000000001', 'Admin',  'KB 管理员：读写删 + 管理', '["kb.read","kb.write","kb.delete","kb.manage","ace.manage"]', TRUE),
    ('dddddddd-0000-4000-d000-000000000002', 'Editor', '内容编辑：读写',          '["kb.read","kb.write"]', TRUE),
    ('dddddddd-0000-4000-d000-000000000003', 'Viewer', '只读：仅查看',            '["kb.read"]', TRUE),
    ('dddddddd-0000-4000-d000-000000000004', 'Deny',   '显式拒绝',                '[]', TRUE)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- v4: Space 管理员（关联具体 User）+ Space 准入组（关联用户组）
-- ============================================================

CREATE TABLE IF NOT EXISTS space_admins (
    space_id   UUID       NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    user_id    UUID       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL CHECK (role IN ('owner', 'admin')),
    granted_by UUID       REFERENCES users(id),
    created_at TIMESTAMP  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (space_id, user_id)
);

CREATE TABLE IF NOT EXISTS space_groups (
    id         UUID       PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id   UUID       NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    group_id   UUID       NOT NULL REFERENCES user_groups(id) ON DELETE CASCADE,
    joined_at  TIMESTAMP  NOT NULL DEFAULT NOW(),
    UNIQUE(space_id, group_id)
);
CREATE INDEX IF NOT EXISTS idx_sg_space ON space_groups(space_id);
CREATE INDEX IF NOT EXISTS idx_sg_group ON space_groups(group_id);

-- ============================================================
-- v4: Group 管理员（管"人"，与 Space 管理员解耦）
-- ============================================================

CREATE TABLE IF NOT EXISTS group_admins (
    group_id   UUID       NOT NULL REFERENCES user_groups(id) ON DELETE CASCADE,
    user_id    UUID       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL CHECK (role IN ('owner', 'admin')),
    granted_by UUID       REFERENCES users(id),
    created_at TIMESTAMP  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (group_id, user_id)
);

-- ============================================================
-- v3: Knowledge Base（知识库）
-- visibility: space_wide（Space 内全员可见）| restricted（仅 kb_members 可见）
-- ============================================================

CREATE TABLE IF NOT EXISTS knowledge_bases (
    id          UUID         PRIMARY KEY,
    space_id    UUID         NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    name        VARCHAR(128) NOT NULL,
    description TEXT         DEFAULT '',
    visibility  VARCHAR(16)  NOT NULL DEFAULT 'space_wide'
                        CHECK (visibility IN ('space_wide', 'restricted')),
    deleted_at  TIMESTAMP    NULL,
    created_by  UUID         NOT NULL REFERENCES users(id),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_kb_space ON knowledge_bases(space_id);
CREATE INDEX IF NOT EXISTS idx_kb_visibility ON knowledge_bases(space_id, visibility);

-- ============================================================
-- v4: ACE 核心权限表（主体 → 资源 → 角色）
-- principal: group | user, resource: kb | document (Phase 3)
-- effect: allow | deny（deny 始终覆盖 allow）
-- ============================================================

CREATE TABLE IF NOT EXISTS access_control_entries (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    space_id        UUID         NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    resource_type   VARCHAR(16)  NOT NULL CHECK (resource_type IN ('kb', 'document')),
    resource_id     UUID         NOT NULL,
    principal_type  VARCHAR(16)  NOT NULL CHECK (principal_type IN ('group', 'user')),
    principal_id    UUID         NOT NULL,
    role_id         UUID         NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    effect          VARCHAR(8)   NOT NULL DEFAULT 'allow' CHECK (effect IN ('allow', 'deny')),
    priority        INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE(space_id, resource_type, resource_id, principal_type, principal_id)
);
CREATE INDEX IF NOT EXISTS idx_ace_space     ON access_control_entries(space_id);
CREATE INDEX IF NOT EXISTS idx_ace_resource  ON access_control_entries(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_ace_principal ON access_control_entries(principal_type, principal_id);

-- ============================================================
-- 文档管理（修改自 v2）
-- 删除: owner_scope_type, owner_scope_id, classification,
--       visible_departments, security_level, chunk_access_level
-- 新增: kb_id
-- ============================================================

CREATE TABLE IF NOT EXISTS document_meta (
    id               UUID         PRIMARY KEY,
    filename         VARCHAR(255) NOT NULL,
    file_type        VARCHAR(16)  NOT NULL,
    file_size        BIGINT       NOT NULL,
    file_path        VARCHAR(512) NOT NULL,
    space_id         UUID         NOT NULL REFERENCES spaces(id),  -- v4: 冗余 space_id 加速查询
    kb_id            UUID         NOT NULL REFERENCES knowledge_bases(id),
    status           VARCHAR(16)  NOT NULL DEFAULT 'active'
                             CHECK (status IN ('active', 'soft_deleted')),
    deleted_at       TIMESTAMP    NULL,
    expires_at       TIMESTAMP    NULL,
    doc_effective_date DATE       NOT NULL DEFAULT CURRENT_DATE,
    doc_expiry_date  DATE         NULL,
    doc_version      VARCHAR(32)  NULL,
    contributor_id   UUID         REFERENCES users(id),
    approval_status  VARCHAR(16)  NOT NULL DEFAULT 'approved'
                             CHECK (approval_status IN ('pending','approved','rejected')),
    tags             JSONB,
    ingest_status    VARCHAR(16)  NOT NULL DEFAULT 'pending'
                             CHECK (ingest_status IN ('pending','processing','completed','failed')),
    uploaded_by      UUID         NOT NULL REFERENCES users(id),
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dm_kb ON document_meta(kb_id);
CREATE INDEX IF NOT EXISTS idx_dm_uploader ON document_meta(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_dm_approval ON document_meta(approval_status);
CREATE INDEX IF NOT EXISTS idx_dm_ingest ON document_meta(ingest_status);
CREATE INDEX IF NOT EXISTS idx_dm_status ON document_meta(status);
CREATE INDEX IF NOT EXISTS idx_dm_expires ON document_meta(expires_at);
CREATE INDEX IF NOT EXISTS idx_dm_effective ON document_meta(doc_effective_date);
CREATE INDEX IF NOT EXISTS idx_dm_expiry ON document_meta(doc_expiry_date);
CREATE INDEX IF NOT EXISTS idx_dm_created ON document_meta(created_at);

-- ============================================================
-- 文档上传审批
-- ============================================================

CREATE TABLE IF NOT EXISTS document_approvals (
    id              UUID         PRIMARY KEY,
    document_id     UUID         NOT NULL REFERENCES document_meta(id) ON DELETE CASCADE,
    submitted_by    UUID         NOT NULL REFERENCES users(id),
    submitted_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    reviewed_by     UUID         REFERENCES users(id),
    reviewed_at     TIMESTAMP,
    status          VARCHAR(16)  NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','approved','rejected')),
    review_comment  TEXT,
    action_type     VARCHAR(16)  NOT NULL DEFAULT 'upload'
                            CHECK (action_type IN ('upload','update','delete')),
    pending_file_path VARCHAR(512),
    pending_metadata  JSONB       DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_da_document ON document_approvals(document_id);
CREATE INDEX IF NOT EXISTS idx_da_status ON document_approvals(status);

-- ============================================================
-- 对话与消息（修改自 v2）
-- 删除: scope_type, scope_id
-- 新增: kb_id（可选，对话不一定绑定 KB）
-- ============================================================

CREATE TABLE IF NOT EXISTS conversations (
    id              UUID         PRIMARY KEY,
    user_id         UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           VARCHAR(255),
    kb_id           UUID         REFERENCES knowledge_bases(id),
    space_id        UUID         REFERENCES spaces(id),
    status          VARCHAR(16)  NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active', 'archived')),
    message_count   INTEGER      DEFAULT 0,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_conv_user_status ON conversations(user_id, status);
CREATE INDEX IF NOT EXISTS idx_conv_kb ON conversations(kb_id);
CREATE INDEX IF NOT EXISTS idx_conv_space ON conversations(space_id);
CREATE INDEX IF NOT EXISTS idx_conv_updated ON conversations(updated_at);

CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID          NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role            VARCHAR(16)   NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content         TEXT          NOT NULL,
    tokens_used     INTEGER,
    sources         JSONB,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_msg_conv_time ON messages(conversation_id, created_at);

-- ============================================================
-- 向量存储（修改自 v2）
-- 删除: owner_scope_type, owner_scope_id, classification,
--       visible_departments, security_level, chunk_access_level
-- 新增: kb_id
-- ============================================================

CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id            VARCHAR(64)   PRIMARY KEY,
    doc_id        VARCHAR(64)   NOT NULL,
    chunk_index   INTEGER       NOT NULL,
    chunk_text    TEXT          NOT NULL,
    embedding     VECTOR(1024)  NOT NULL,
    kb_id         VARCHAR(64)   NOT NULL,
    status        VARCHAR(16)   NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'soft_deleted')),
    doc_effective_date DATE     NULL,
    doc_expiry_date  DATE       NULL,
    doc_version      VARCHAR(32) NULL,
    source_file   VARCHAR(512)  NOT NULL DEFAULT '',
    -- v5: 混合检索新增
    content_with_weight TEXT     NULL,         -- 关键词加权重复文本（BM25 增强）
    fts            tsvector      NULL,         -- PostgreSQL 全文搜索向量
    created_at    BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_kc_doc_id ON knowledge_chunks(doc_id);
CREATE INDEX IF NOT EXISTS idx_kc_kb ON knowledge_chunks(kb_id);
CREATE INDEX IF NOT EXISTS idx_kc_status ON knowledge_chunks(status);
-- v5: HNSW 索引替代 IVFFlat，更高召回率
CREATE INDEX IF NOT EXISTS idx_kc_embedding_hnsw
    ON knowledge_chunks
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);
-- v5: 全文搜索 GIN 索引
CREATE INDEX IF NOT EXISTS idx_kc_fts
    ON knowledge_chunks USING GIN (fts);

-- v5: 自动更新 fts 触发器
CREATE OR REPLACE FUNCTION update_kc_fts()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fts = to_tsvector('simple',
        regexp_replace(COALESCE(NEW.content_with_weight, NEW.chunk_text), '([一-鿿])', ' \\1 ', 'g'));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER IF NOT EXISTS trg_update_kc_fts
    BEFORE INSERT OR UPDATE OF chunk_text, content_with_weight
    ON knowledge_chunks
    FOR EACH ROW
    EXECUTE FUNCTION update_kc_fts();

-- ============================================================
-- v3: 管理员操作日志（审计）
-- action 自由文本：member.add, member.remove, member.change_role,
--         kb.create, kb.trash, kb.restore, kb.delete_permanent, kb.update,
--         kb_member.add, kb_member.remove, kb_member.change_role,
--         doc.approve, doc.reject, doc.trash, doc.restore, doc.delete_permanent,
--         space.create, space.archive
-- ============================================================

CREATE TABLE IF NOT EXISTS admin_action_logs (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id  UUID         NOT NULL REFERENCES users(id),
    space_id     UUID         NOT NULL REFERENCES spaces(id),
    action       VARCHAR(32)  NOT NULL,
    target_type  VARCHAR(32)  NOT NULL,
    target_id    VARCHAR(64)  NOT NULL,
    target_name  VARCHAR(256),
    details      JSONB        DEFAULT '{}',
    created_at   TIMESTAMP    DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_aal_space_time ON admin_action_logs(space_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_aal_operator ON admin_action_logs(operator_id);
CREATE INDEX IF NOT EXISTS idx_aal_action ON admin_action_logs(action);

-- ============================================================
-- 检索质量反馈
-- ============================================================

CREATE TABLE IF NOT EXISTS retrieval_feedback (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- 来源标识
    source          VARCHAR(20)  NOT NULL,   -- 'web_chat' | 'mcp'
    user_id         VARCHAR(50),
    space_id        VARCHAR(50),
    session_id      VARCHAR(50),

    -- 查询信息 (模块 1~2)
    original_query  TEXT         NOT NULL,
    rewritten_query TEXT,
    kb_ids          JSONB,
    keywords        JSONB,
    resolved_filters JSONB,

    -- 检索指标 (模块 3)
    retrieval_path  VARCHAR(50),            -- 'simple' | 'dag'
    top_k           INT,
    min_score       REAL,
    latency_breakdown JSONB,                -- {dense_ms, bm25_ms, splade_ms, rerank_ms, total_ms}
    recall_stats    JSONB,                  -- {dense_hits, bm25_hits, splade_hits}
    reranked_count  INT,
    filtered_count  INT,
    llm_tokens      JSONB,                  -- {planner, hyde, extract}_tokens

    -- 结果快照 (模块 4) — 不存全文，只存摘要
    chunks          JSONB,                  -- [{chunk_id, doc_id, doc_title, score, snippet}]

    -- 生成内容 (模块 5) — 截断至 500 字符
    generated_response TEXT,

    -- LLM-as-a-Judge (模块 6) — 异步评估
    faithfulness_score   REAL,
    answer_relevance     REAL,
    context_relevance    REAL,
    judge_model          VARCHAR(50),
    judge_latency_ms     INT,

    -- 反馈结果 (模块 7) — 异步填入
    rating          VARCHAR(10),            -- 'like' | 'dislike'
    feedback_reason VARCHAR(100),
    feedback_at     TIMESTAMPTZ,

    -- 扩展
    extra           JSONB,

    -- ★ v12: 全量阶段追踪
    stages_detail   JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_rf_created ON retrieval_feedback(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rf_source ON retrieval_feedback(source);
CREATE INDEX IF NOT EXISTS idx_rf_rating ON retrieval_feedback(rating);
CREATE INDEX IF NOT EXISTS idx_rf_user ON retrieval_feedback(user_id);
